<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<article class="col-sm-12">
    <div class="prod-list">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
	<script defer src="<?php echo $this->getSkinUrl() . 'js/script_list.js'; ?>"></script>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(220); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            <?php // Product description ?>
            <div class="product-shop">
                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product) ?>
                <?php endif; ?>
                <?php echo $this->getPriceHtml($_product, true) ?>

                <?php if($_product->isSaleable()): ?>
                  <!--  <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p> -->
                <?php else: ?>
                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                <?php endif; ?>
                <div class="desc std">
                    <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                </div>
                <ul class="add-to-links">
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                    <?php endif; ?>
                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                        <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                    <?php endif; ?>
                </ul>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>
	<script defer src="<?php echo $this->getSkinUrl() . 'js/script_grid.js'; ?>"></script>
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>

    <ul class="list-unstyled list-inline products_list clearfix">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <li>
            <div class="prod-item">
                <div class="item-pict">
                    <a href="<?php echo $_product->getProductUrl() ?>">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(140); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                    </a>
                </div>
                <div class="discr">
                    <div class="cast"><?php echo $this->getPriceHtml($_product, true) ?></div>
                    <div class="title">
                        <a href="<?php echo $_product->getProductUrl() ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                    </div>
                </div>
                <div class="add-to-buttons">
                    <?php if($_product->isSaleable()): ?>
						<?php if( $_product->getTypeId() == 'simple' ): ?>
							<button type="button" title="<?php echo $this->__('Buy') ?>" class="btn btn-success" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Buy') ?></span></span></button>
						<?php else : ?>
							<a title="<?php echo $this->__('Buy') ?>" class="btn btn-success" href="<?php echo $_product->getProductUrl() ?>?modif=1"><span><span><?php echo $this->__('Buy') ?></span></span></a>
						<?php endif; ?>
                    <?php endif; ?>
                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                        <a href="<?php echo $_compareUrl ?>" class="link-compare btn btn-info" ><?php echo $this->__('Compare') ?></a>
                    <?php endif; ?>
                </div>
            </div>
        </li>
    <?php endforeach ?>
    </ul>
        <script>
            Equals(jQuery('.products_list li .cast'))
        </script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>

    <div class="prod-list">
        <ul class="nav nav-tabs tab-success">
            <li class="active"><a id="tab-prod-new" href="#prod-new" data-toggle="tab"><span>Новинки</span></a></li>
            <li class=""><a id="tab-prod-sales" href="#prod-sales" data-toggle="tab"><span>Распродажа</span></a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="prod-new">
                <?php echo $this->getChildHtml('product_new') ?>
            </div>
            <div class="tab-pane" id="prod-sales">
                <?php echo $this->getChildHtml('product_sale') ?>
            </div>
        </div>
    </div> <!-- End prod-list -->

</article>
<?php endif; ?>

