<?php
$var = Mage::registry('license_msg');
if($var==null){

?>				
				<style>
				.sample-csv-item{margin:1px;/* border:1px dotted black; */}
				.sample-csv-item h3{background:#666e73;color:white;padding:3px 3px 3px 10px;}
				.sample-csv-item ul{margin:10px}
				.sample-csv-item a {font-size: 14px;text-decoration: none;}				
				</style>				
				<div id="sample_csv_content">
				
				<div class="sample-csv-item">
				<h3>Simple Products Sample CSV </h3>
				<ul class="sample-csv-ul">
					<li>
						<a href="http://magento.capacitywebservices.com/csv/import.csv">Few Products Columns Sample Import CSV </a>
					</li>
					
					<li>
						<a href="http://magento.capacitywebservices.com/csv/all_import_products.csv">All Products Columns Sample Import CSV </a>
					</li>

					<li>
						<a href="http://magento.capacitywebservices.com/csv/import_with_minimum_field.csv">Import with Min Required Fields</a>
					</li>	
					
				

					<li>
						<a href="http://magento.capacitywebservices.com/csv/new_product_import_with_custom_options.csv">Import with Custom Options</a>
					</li>										
					
					<li>
						<a href="http://magento.capacitywebservices.com/csv/import_with_category.csv">Import with Category</a>
					</li>

					<li>
						<a href="http://magento.capacitywebservices.com/csv/import_with_subcategories.csv">Import with Sub-Category</a>
					</li>

					<li>
						<a href="http://magento.capacitywebservices.com/csv/import_with_categoryIDs.csv">Import with Category IDs</a>
					</li>
						
					<li>
						<a href="http://magento.capacitywebservices.com/csv/import_with_multi_store.csv">Import with Multi Store CSV </a>
					</li>

					<li>
						<a href="http://magento.capacitywebservices.com/csv/import_with_multi_website.csv">Import with Multi Website CSV </a>
					</li>					
						

					
				</ul>
	<div class="sample-csv-item">
						<h3>Configurable Products CSV</h3>
						<ul class="sample-csv-ul">
							<li>
								<a href="http://magento.capacitywebservices.com/csv/import_configurable_products.csv">Import Configurable Products with Simple Products </a>
							</li>
							
						</ul>
					</div>

					<div class="sample-csv-item">
						<h3>Bundle Products CSV</h3>
						<ul class="sample-csv-ul">
							<li>
								<a href="http://magento.capacitywebservices.com/csv/import_bundle_products.csv">Import Bundle Products with Simple Products </a>
							</li>
							
						</ul>
					</div>						
					<div class="sample-csv-item">
						<h3>Grouped Products CSV</h3>
						<ul class="sample-csv-ul">
							<li>
								<a href="http://magento.capacitywebservices.com/csv/import_grouped_products.csv">Import Grouped Products with Simple Products </a>
							</li>
							
						</ul>
					</div>	
					<div class="sample-csv-item">
						<h3>Downloadable Products CSV</h3>
						<ul class="sample-csv-ul" >
							<li>
								<a href="http://magento.capacitywebservices.com/csv/import_downloadable_products.csv">Import Downloadable Products with Simple Products </a>
							</li>
							
						</ul>
					</div>	

					<div class="sample-csv-item" style="clear:both;width:100%;height:140px">
						<h3>Update Products CSV</h3>
						<ul class="sample-csv-ul">
					<li>
						<a href="http://magento.capacitywebservices.com/csv/update_quantity.csv">Update Quantity</a>
					</li>

					<li>
						<a href="http://magento.capacitywebservices.com/csv/update_price.csv">Update Price</a>
					</li>					
					
					<li>
						<a href="http://magento.capacitywebservices.com/csv/update_images.csv">Update Images</a>
					</li>
							
					<li>
						<a href="http://magento.capacitywebservices.com/csv/assign_related_upsell_crossell_products.csv">Assign Related, Upsell & Crosssell Products</a>
					</li>
					
					
					<li>
						<a href="http://magento.capacitywebservices.com/csv/assign_group_price.csv">Assign Group Price</a>
					</li>

					<li>
						<a href="http://magento.capacitywebservices.com/csv/assign_tier_price.csv">Assign Tier Price</a>
					</li>

					<li>
						<a href="http://magento.capacitywebservices.com/csv/storewise-custom-option-update.csv">Update Custom Options Store Wise</a>
					</li>					

					<li>
						<a href="http://magento.capacitywebservices.com/csv/delete-products.csv">Delete Products</a>
					</li>					

					
				</ul>
			</div>

					
			</div>
				
				
				</div>
				<?php 
}else{
}
 //echo $this->getRunButtonHtml() ?><br/>