<?php
$hlr = $this->helper("amscheckout");
$hlr->initAddress($this->getAddress());
?>
<?php
if(!$this->isCustomerLoggedIn()) {

    echo $this->__("Мы сгенерируем вам пароль");

    $repl = array(
        "amscheckout-control" => "amscheckout-control amscheckout-control-checkbox",
        "amscheckout-label" => "amscheckout-label amscheckout-label-radio"
    );
    $_createAccount = array(
        'field_key' => 'billing_create_account',
        'column_position' => '100',
        'field_required' => 0,
        'field_label' => $this->__("Я введу пароль самостоятельно")
    );
    echo $hlr->getBeforeControlHtml($_createAccount, $repl);?>
		<input type="checkbox" id="billing_create_account" name="billing[create_account]" style="margin: 2px 0px 0px 5px;" />
	<?php
    echo $hlr->getAfterControlHtml($_createAccount);

    $repl = array(
        "amscheckout-row" => "amscheckout-row amscheckout-password",
    );
	
	echo '<div class="create_pass_row" style="display: none;">';
	
    echo $hlr->getBeforeControlHtml($passwordField, $repl);?>
	
		<div class="input-group">
			<div class="input-group-addon">
				<label for="billing:password">Пароль</label>
			</div>
			<div class="input-box">
				<input type="password" name="billing[confirm_password]" title="<?php echo $this->escapeHtml($passwordField['field_label']) ?>" id="billing:confirm_password" class="input-text validate-password <?php $passwordField['field_required'] ? "required-entry" : ""?>" />
			</div>
		</div>
		
	<?php
    echo $hlr->getAfterControlHtml($passwordField);

    $repl = array(
        "amscheckout-row" => "amscheckout-row amscheckout-password",
    );
    echo $hlr->getBeforeControlHtml($passwordRepeatField, $repl);?>
	<div class="input-group">
			<div class="input-group-addon">
				<label for="billing:password">Повторите пароль</label>
			</div>
			<div class="input-box">
				<input type="password" name="billing[confirm_password]" title="<?php echo $this->escapeHtml($passwordField['field_label']) ?>" id="billing:confirm_password" class="input-text validate-cpassword <?php $passwordField['field_required'] ? "required-entry" : ""?>" />
			</div>
		</div>
	<?php
    echo $hlr->getAfterControlHtml($passwordRepeatField);
	echo '</div>';
}
?>

<script>
	jQuery(document).ready(function(){
		jQuery("#billing_create_account").click(function(){
			if (jQuery(this).prop('checked')) {
				jQuery(".create_pass_row").css('display', 'block');
			} else {
				jQuery(".create_pass_row").css('display', 'none');
			}
		});
	});
</script>