<div class="form-group">
    <div class="clearfix">
        <div class="col-sm-7 col-sm-push-5 " id="checkout-review-load">
            <?php echo $this->getChildHtml('info') ?>
        </div>
        <div class="col-sm-5 col-sm-pull-7">
            <button type="button" title="<?php echo $this->__('Place Order') ?>" class="btn btn-success-gray btn-lg" onclick="completeCheckout();">
                <?php echo $this->__('Place Order') ?>
            </button>
        </div>
    </div>
</div>
