<?php
/**
* @author Amasty Team
* @copyright Amasty
* @package Amasty_Conf
*/
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    $imageWidth = (int)Mage::getStoreConfig('amconf/size/preview_width');
    $imageHeight = (int)Mage::getStoreConfig('amconf/size/preview_height');
    $smallImageSize = (int)Mage::getStoreConfig('amconf/size/thumb');
    $itemCount = (int)Mage::getStoreConfig('amconf/carousel/visible_items');
?>
<?php if ('true' == (string) Mage::getConfig()->getNode('modules/Amasty_Label/active')): ?>
                <div class="amlabel-div">
                <?php echo Mage::helper('amlabel')->getLabels($_product, 'product') ?>
 <?php endif; ?>
<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
<div class="product-image">
    <?php
        $_img = '<img width="'. $imageWidth .'" height="'. $imageHeight .'" id="amasty_zoom"
         src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($imageWidth, $imageHeight).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" class="big_img" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>

	<?php if ((date("Y-m-d") >= substr($_product->getNewsFromDate(), 0, 10)) && ((date("Y-m-d") <= substr($_product->getNewsToDate(), 0, 10)) || (substr($_product->getNewsToDate(), 0, 10) == ''))) : ?>
		<div class="photo-credits">
			<div class="prod-mark">Новинка</div>
		</div>
	<?php endif ?>
</div>

<?php else: ?>
<div class="product-image">
    <?php
        $_img = '<img id="amasty_zoom" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($imageWidth, $imageHeight).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" class="big_img" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</div>

<?php endif; ?>
<?php if ('true' == (string)Mage::getConfig()->getNode('modules/Amasty_Label/active')): ?>
                </div>
            <?php endif; ?>

<?php if (count($this->getGalleryImages()) > 1): ?>
<div class="more-views">
    <h2 style="display: none;"><?php echo $this->__('More Views') ?></h2>
    <div class="amasty_gallery_box">
        <div id="amasty_gallery">
             <?php foreach ($this->getGalleryImages() as $_image): ?>
                <a class="fancybox" href="<?php echo Mage::getStoreConfig('amconf/lightbox/thumbnail_lignhtbox')?$this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile()):"#"; ?>" data-image="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($imageWidth, $imageHeight); ?>" data-zoom-image="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile()); ?>"  >
                    <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($smallImageSize); ?>" width="58<?php //echo $smallImageSize;?>" height="58<?php //echo $smallImageSize;?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>"  title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"/>
                </a>
             <?php endforeach; ?>
        </div> 
        <?php if (count($this->getGalleryImages()) > $itemCount && Mage::getStoreConfig('amconf/carousel/enable')): ?>
            <div id="prevGallery" style="top:<?php echo $smallImageSize/2 - 17;?>px" class="MagicScrollArrows jcarousel-control-prev"></div>
            <div id="nextGallery" style="top:<?php echo $smallImageSize/2 - 17;?>px" class="MagicScrollArrows jcarousel-control-next"></div>
             <?php if (Mage::getStoreConfig('amconf/carousel/pagination')): ?>
                <div id="ampagination"></div>
             <?php endif; ?>
        <?php endif; ?>
     </div>
</div>
<?php endif; ?>
<script type="text/javascript" >
    AmZoomerObj = new AmZoomer(<?php echo Mage::helper('amconf/zoom')->jsParam()?>);
    AmZoomerObj.loadCarousel();
</script>