<script type="text/javascript">
    //<![CDATA[   
    window.opConfig = new Product.Options(<?php echo $this->getJsonConfig() ?>);
    $('product_addtocart_form').encoding = 'multipart/form-data';
    //]]>
</script>
<?php if (count($this->getOptions())): ?>
<dl>
<input type="hidden" name="bundle_has_custom_options" value="1"/>
<?php $_options = Mage::helper('core')->decorateArray($this->getOptions()) ?>
<?php foreach($_options as $_option): ?>
    <?php echo $this->getOptionHtml($_option) ?>
<?php endforeach; ?>
</dl>
<script type="text/javascript">
    $$('#product-options-wrapper dl').each(function(label) {
        label.removeClassName('last');
    });
    $$('#SCPcustomOptionsDiv dl').each(function(label) {
        label.addClassName('last');
    });
</script>
<div class="no-display">
        <?php $count = 0;foreach($this->getImportAttribute() as $id => $name):?>
            <input class="<?php if($count == 0) echo 'first';?>" type="hidden" name="<?php echo $name ?>" id="<?php echo $id ?>" value=""/>
        <?php $count++; endforeach; ?>
</div>
<?php endif; ?>