<aside class="sidebar col-sm-3">
    <div class="podbor block-gl">
        <h3>Подбор оборудования</h3>
        <p class="text-muted">Наши специалисты продумалиоптимальные схемы для различных типов и областей применения, теперь выбор стал удобнее и проще.</p>
        <form>
            <div class="form-group">
                <select class="form-control">
                    <option>Тип оборудования</option>
                    <option>Экраны</option>
                    <option>Интерактивное оборудование</option>
                    <option>Акустические системы</option>
                    <option>Кабели</option>
                </select>
            </div>
            <div class="form-group">
                <select class="form-control">
                    <option>Область применения</option>
                    <option>Экраны</option>
                    <option>Интерактивное оборудование</option>
                    <option>Акустические системы</option>
                    <option>Кабели</option>
                </select>
            </div>
            <div class="form-group slider-range">
                <label class="slider-label" for="amount">Цена</label>
                <div class="clearfix">
                    <div id="range-min" class="range-min">от 3500 <span class="rub">i</span></div>
                    <div id="range-max" class="range-max">до 27990 <span class="rub">i</span></div>
                </div>
                <div id="slider-range"></div>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success btn-max">Подобрать оборудование</button>
            </div>
        </form>
    </div>
    <div class="block-gl">
        <h3>Баннер</h3>
        <p class="text-muted">240 x 400</p>
        <p>Или текстовый блок для продвижения</p>
    </div>
</aside>